### ISSUE TITLE
add option to scale geometry

### ISSUE THREAD

**Issue by Shimwell** [fusion-energy/cad_to_h5m#26]
add the option to scale the geometry in a similar manner to the previous script https://github.com/fusion-energy/paramak/blob/8368d7c9f5645bbd5e97c98a00f7e41df0483aa3/paramak/make_faceteted_neutronics_model.py#L214-L217

**Comment by LukeLabrie** [comment]
Hey Jonathan, I made a very simple version of this option locally. At some point between CAD and OpenMC, my volumes would all get scaled down x100. I just copied the function from the link above, added an optional scaling factor argument to the cad_to_h5m function which then gets sent to the scale_geometry function. Also, instead of looping over the volumes I just used:

`cubit> vol all scale <scaling_factor>`

It is working well for my purposes. Happy to share if it is at all helpful. 

Thanks for sharing this repo by the way, it's been helpful for my workflow recently. 

Best,
Luke

**Comment by Shimwell** [comment]
Ah yes that sounds like a units thing. CAD often defaults to mm while we need ignore the units and just assume the numbers are in cm as cm is needed for neutronics simulations at the moment.

I would be keen to see that old scale all function from the have first link and incorporate into this code.

https://github.com/fusion-energy/paramak/blob/e49940a68cd0d70332eacbba5e0b2d53e9fc48de/paramak/make_faceteted_neutronics_model.py#L214

The dictionary of STP files and materials would need to allow another entry but perhaps that is ok.

Then individual STP files can be scaled by different amounts.

I'm happy to do this sometime but PR are always welcome if you are keen.

Would you prefer a single arg that controls the scaling factor for all the STP files, if so then we can add that and not worry about changing the STP files and materials dictionary

**Comment by LukeLabrie** [comment]
Sorry, just seeing this -- looks like you've added the feature. Thanks!

When I added this locally I just used a single scaling factor arg because that was all I needed but this looks more thorough. Next time I'll try a PR if it saves you time (I held off since I'm still a bit new to the github workflow).

**Comment by Shimwell** [comment]
Thanks for getting back to us on this Luke.  Yes we merged in the scale feature. I've not used or tested it much so do let me know if you find any problems.

Always happy to walk you through a PR next time. We can even do a PR for a simple typo fix or refactor if you just want to go through the process sometime.

**Comment by LukeLabrie** [comment]
Thanks. That would be really helpful. 

Currently working (locally) on adding the option to define implicit complements on materials. Would you be interested in incorporating that?

**Comment by Shimwell** [comment]
Sure that sounds good, would you be able to write up an issue as a first stage and explain the idea and motivation
